// Experiences
export const experiences = [
  {
    title: "Programmer",
    company_name: "Similan Technology Co., Ltd.",
    location: "Bang Na, Bangkok",
    iconBg: "#FBA834",
    icon: "FaDesktop",
    date: "06/2023 - 05/2024",
    points: [
      `+ Developing Android app for handheld device (POD system) with React-Native.`,
      `+ Developing RESTful API for data interface to third party (E-Commerce) with ASP.NET API.`,
      `+ Developing and enhancing Web app with React, NestJS.`,
    ],
  },
  {
    title: "Grocery Assistant",
    company_name: "Family's Grocery Store",
    location: "Wapi Pathum District, Maha Sarakham",
    iconBg: "#333A73",
    icon: "FaStore",
    date: "01/2021 - 01/2023",
    points: [
      `+ Maintained and replenished stock according to store merchandising layout, ensuring consistent product availability.`,
      `+ Completed deliveries with smile and patient, personalised service.`,
    ],
  },
  {
    title: "AutoCAD Designer",
    company_name: "Freelancer",
    location: "Bang Phli District, Samut Prakan",
    iconBg: "#387ADF",
    icon: "FaDraftingCompass",
    date: "01/2019 - 01/2020",
    points: [`+ Designing pieces according to the given specifications.`],
  },
  {
    title: "General Worker",
    company_name: "Kanjana Tailor Shop",
    location: "Khan Na Yao, Bangkok",
    iconBg: "#50C4ED",
    icon: "FaTshirt",
    date: "12/2017 - 11/2018",
    points: [
      `+ Laying fabric from fabric rolls, layer by layer, to prepare for fabric pattern layout, and using a cutting machine.`,
      `+ Handing fabric pieces to seamstresses for assembly, packaging finished products, and delivering them to customers.`,
    ],
  },
]

// Skills
export const works = [
  {
    title: "Booking Resort & Ticket",
    description:
      "A website for booking hotels and tickets to attractions, offering various interesting information.",
    thumbnail: "works/resort/thumbnail.png",
    tags: ["React", "Zustand", "MUI", "NestJS", "SQL"],
    images: [],
    link_github: null,
    link_web: "https://www.nongnooch.io/nongnooch-resort/home",
    category: ["MOBILE", "REACT"],
  },
  {
    title: "Digital Assets",
    description:
      "A website for collecting digital assets, enabling auctions and trading, with Omise as the payment gateway.",
    thumbnail: "works/digital-assets/thumbnail.png",
    tags: ["React", "Redux", "MUI", "NestJS", "SQL"],
    images: [],
    link_github: null,
    link_web: "https://www.nongnooch.io/Nongnooch(NDA)/home",
    category: "REACT",
  },
  {
    title: "Pics Search",
    description:
      "A website for searching various images, integrated with the Unsplash API.",
    thumbnail: "works/pics-search/thumbnail.png",
    images: [],
    tags: ["React"],
    link_github: "https://github.com/02angeJuice/pics-search",
    link_web: "https://pics-search-api.netlify.app/",
    category: "REACT",
  },
  {
    title: "The Burger",
    description:
      "A website for simulating order placement and creating burgers simultaneously.",
    thumbnail: "works/burger/thumbnail.png",
    images: [],
    tags: ["React", "Redux"],
    link_github: "https://github.com/02angeJuice/the-burger-remake",
    link_web: "https://the-burger-remake.netlify.app",
    category: "REACT",
  },
  {
    title: "Grocify Homepage",
    description: "A homepage designed for a grocery store website.",
    thumbnail: "works/grocify-home/thumbnail.png",
    images: [],
    tags: ["React", "Tailwind"],
    link_github: "https://github.com/02angeJuice/workshop-grocery-tailwind",
    link_web: "https://grocery-hompage.netlify.app",
    category: "REACT",
  },
  {
    title: "Landing Homepage",
    description: "A simple landing page.",
    thumbnail: "works/starter-landing/thumbnail.png",
    images: [],
    tags: ["React", "Tailwind"],
    link_github: "https://github.com/02angeJuice/workshop-landing-tailwind",
    link_web: "https://starter-landing-homepage.netlify.app",
    category: "REACT",
  },
  {
    title: "Handheld Express App",
    description:
      "A mobile app for handheld devices used in parcel management through barcode scanning.",
    thumbnail: "works/express/thumbnail.jpg",
    images: [
      "works/express/1.jpg",
      "works/express/2.jpg",
      "works/express/3.jpg",
      "works/express/4.jpg",
      "works/express/5.jpg",
      "works/express/6.jpg",
      "works/express/7.jpg",
    ],
    tags: ["React Native", "Redux", "NestJS", "SQL"],
    link_github: null,
    link_web: null,
    category: ["MOBILE"],
  },
  {
    title: "Auto Delete Todo",
    description: "Simple todo list with auto delete feature",
    thumbnail: "works/todo/thumbnail.png",
    images: [],
    tags: ["React", "Zustand", "MUI"],
    link_github: "https://github.com/02angeJuice/todo-list",
    link_web: "https://auto-todo-list.netlify.app",
    category: "REACT",
  },

  {
    title: "Form Validation",
    description: "Form validation with React and Redux",
    thumbnail: "works/form-validation/thumbnail.png",
    images: [],
    tags: ["React", "Redux", "Tailwind"],
    link_github: "https://github.com/02angeJuice/practice_2",
    link_web: "https://demo-form-validation.netlify.app/",
    category: "REACT",
  },
]

export const tech_stacks = [
  { name: "HTML", src: "my-self/stacks/html.png" },
  { name: "CSS", src: "my-self/stacks/css.png" },
  { name: "JavaScript", src: "my-self/stacks/js.png" },
  { name: "TypeScript", src: "my-self/stacks/ts.svg" },
  { name: "NodeJS", src: "my-self/stacks/node.svg" },
  { name: "NestJS", src: "my-self/stacks/nestjs.png" },
  { name: "React", src: "my-self/stacks/react.png" },
  { name: "Redux", src: "my-self/stacks/redux.png" },
  { name: "Prisma", src: "my-self/stacks/prisma-2.svg" },
  { name: "SQL", src: "my-self/stacks/sql.png" },
  { name: "MUI", src: "my-self/stacks/mui.svg" },
  { name: "Tailwind", src: "my-self/stacks/tailwind.png" },
  { name: "Postman", src: "my-self/stacks/postman.png" },
  { name: "Github", src: "my-self/stacks/github.png" },
  { name: "Vite", src: "my-self/stacks/vite.png" },
]
